pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test -Dmaven.test.failure.ignore=true'
            }
            post {
                success {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Make Container') {
            steps {
                NAME = sh (
                        script: 'mvn help:evaluate -Dexpression=project.name | grep "^[^\[]"',
                        returnStdout: true
                        ).trim()
                VERSION = sh (
                        script: 'mvn help:evaluate -Dexpression=project.version | grep "^[^\[]"',
                        returnStdout: true
                        ).trim()

                sh "docker build -t srknbdk/${NAME}:${VERSION}-${env.BUILD_ID} ."
                sh "docker tag srknbdk/${NAME}:${VERSION}-${env.BUILD_ID} srknbdk/${NAME}:latest"
      }
    }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
